## Broadcasting in Python

In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [2]:
cal = A.sum(axis=0) # 0 - sum vertically, 1- sum horizontally
print(cal)

[ 59.  239.  155.4  76.9]


In [4]:
percentage = 100*A/cal.reshape(1,4) # broadcasting
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


A is a 3 x 4 matrix and cal is a 1 x 4 matrix

In [28]:
A = np.array([[1,2,3,4]])
print(A)

[[1 2 3 4]]


In [27]:
print(A + 100)

[[101 102 103 104]]


In [33]:
A = np.array([[1, 2, 3],
            [4, 5, 6]])
B = np.array([100, 200, 300])

print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[100 200 300]


In [34]:
print(A + B)

[[101 202 303]
 [104 205 306]]
