## Common Errors

In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 1.1585016  -0.54106347 -0.35834903 -0.71191856 -1.92595704]


In [5]:
print(a.shape) # This is called a rank 1 array. It is neither a row 
               # or a column vector

(5,)


In [7]:
print(a.T) # a transpose

[ 1.1585016  -0.54106347 -0.35834903 -0.71191856 -1.92595704]


In [8]:
print(np.dot(a, a.T))

5.979428221824378


In [9]:
a = np.random.randn(5,1) # this is a column vector or a 5 x 1 matrix
print(a)

[[ 1.00132523]
 [-3.06303113]
 [ 0.30277772]
 [-0.21973764]
 [-1.79665931]]


In [10]:
print(a.T)

[[ 1.00132523 -3.06303113  0.30277772 -0.21973764 -1.79665931]]


In [11]:
print(np.dot(a, a.T))

[[ 1.00265222 -3.06709037  0.30317897 -0.22002885 -1.79904031]
 [-3.06709037  9.38215972 -0.92741759  0.67306324  5.50322341]
 [ 0.30317897 -0.92741759  0.09167435 -0.06653166 -0.54398841]
 [-0.22002885  0.67306324 -0.06653166  0.04828463  0.39479368]
 [-1.79904031  5.50322341 -0.54398841  0.39479368  3.22798468]]


a = np.random.randn(1,5) -> a.shapre = (1,5) => row vector

a = np.random.randn(5, 1) -> a.shapre = (5, 1) => column vector

assert(a.shape == (5,1))


### To resphape a rank 1 array

a = a.reshape((5,1))